# SPDX-License-Identifier: CC-BY-4.0
# SPDX-FileCopyrightText: 2025 DB Systel GmbH

changelog:
  categories:
    - title: Features and Fixes
      labels:
        - "*"
      exclude:
        labels:
          - dependencies
          - Renovate
    - title: Dependencies
      labels:
        - dependencies
        - Renovate
