# SPDX-FileCopyrightText: 2024 DB Systel GmbH
#
# SPDX-License-Identifier: Apache-2.0

[project]
name = "compliance-assistant"
version = "1.1.6"
description = "Toolset that helps with creating and interacting with SBOMs, enriching with licensing and copyright information, and checking for Open Source license compliance"
authors = [{ name = "Max Mehl", email = "max.mehl@deutschebahn.com" }]
requires-python = ">=3.10,<4"
readme = "README.md"
license = "Apache-2.0"
keywords = [
    "sbom",
    "compliance",
    "clearlydefined",
    "cyclonedx",
    "spdx",
    "license",
    "copyright",
    "flict",
    "compatibility",
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Console",
    "Topic :: Software Development",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
dependencies = [
    "requests>=2.32.5,<3",
    "flict>=1.3.0,<2",
    "docker>=7.1.0,<8",
    "license-expression>=30.4.4,<31",
    "purl-tools>=0.2.3,<0.3",
]

[project.urls]
Repository = "https://github.com/OpenRailAssociation/compliance-assistant"

[project.scripts]
compliance-assistant = "complassist.main:main"

[dependency-groups]
dev = [
    "ruff>=0.15.10",
    "ty>=0.0.29",
    "bump-my-version>=1.1.2,<2",
]

[tool.uv]
default-groups = "all"

[tool.uv.build-backend]
module-name = ["complassist"]
module-root = ""

[build-system]
requires = ["uv_build>=0.11.6,<0.12.0"]
build-backend = "uv_build"

# FORMATTING and LINTING settings
[tool.ruff]
line-length = 100

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "T",
    "FBT",
    "LOG015",
    "COM812",
    "ERA001",
    "S310",
    "S603",
    "D205",
    "D212",
    "PTH123",
    "FIX002",
    "TD002",
    "TD003",
    "PERF203",
]
[tool.ruff.lint.extend-per-file-ignores]
"complassist/main.py" = ["C901", "PLR0912", "PLR0915"]
[tool.ruff.lint.pydocstyle]
convention = "google"

# TY settings
[tool.ty.src]
include = ["complassist"]

# Bump-My-Version
[tool.bumpversion]
commit = true
tag = true
sign_tags = true
allow_dirty = false
tag_name = "v{new_version}"

[[tool.bumpversion.files]]
filename = "pyproject.toml"
regex = true
search = "^version = \"{current_version}\""
replace = "version = \"{new_version}\""

[[tool.bumpversion.files]]
filename = "uv.lock"
search = """
[[package]]
name = "compliance-assistant"
version = "{current_version}"
"""
replace = """
[[package]]
name = "compliance-assistant"
version = "{new_version}"
"""
