# SPDX-FileCopyrightText: 2024 DB Systel GmbH
#
# SPDX-License-Identifier: Apache-2.0

name: "Reusable Poetry build workflow"
inputs:
  python:
    default: "3.10"
    description: "Value for 'python-version'"
    required: false
    type: string
  poetry_args:
    default: ""
    description: "Additional arguments for the poetry install step'"
    required: false
    type: string
runs:
  using: "composite"
  steps:
    - name: Install poetry
      run: pipx install poetry
      shell: bash
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python }}
        cache: "poetry"
    - name: Install dependencies
      run: poetry install --no-interaction ${{ inputs.poetry_args }}
      shell: bash
